/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerGrid: typeof import('./src/components/AnswerGrid.vue')['default']
    AvatarPic: typeof import('./src/components/AvatarPic.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DrainRing: typeof import('./src/components/DrainRing.vue')['default']
    GatherChoices: typeof import('./src/components/GatherChoices.vue')['default']
    GatherSelect: typeof import('./src/components/GatherSelect.vue')['default']
    HostBar: typeof import('./src/components/HostBar.vue')['default']
    LanguageSwitch: typeof import('./src/components/LanguageSwitch.vue')['default']
    QuizPreview: typeof import('./src/components/QuizPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
  }
}
